services:
  - type: web
    name: credit-sea-app
    env: node
    buildCommand: |
      # Install server dependencies
      npm install
      # Go to client directory
      cd client
      # Clean install client dependencies
      rm -rf node_modules
      npm cache clean --force
      npm install
      # Explicitly install react-scripts
      npm install react-scripts --save
      # Build the React app with CI=false to ignore warnings
      CI=false npm run build
      # Go back and ensure build directory exists
      cd ..
      mkdir -p client/build
      # Copy build files to the right location
      cp -r client/build/* client/build/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: creditsea
          property: connectionString
