services:
  - type: web
    name: credit-sea-app
    env: node
    buildCommand: |
      npm install
      cd client && npm install
      cd client && npm run build
      mkdir -p /opt/render/project/src/client/build
      cp -r client/build/* /opt/render/project/src/client/build/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: creditsea
          property: connectionString
